plugins {
	id 'java'
	id 'application'
}

group = 'de.fraunhofer.iosb.ilt.faaast'
version = '1.0.0-SNAPSHOT'

java {
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

repositories {
	mavenCentral()
}
dependencies {
	implementation project(':faaast-lib')

	implementation "ch.qos.logback:logback-classic:${logback_version}"
	implementation "ch.qos.logback:logback-core:${logback_version}"
	implementation "com.h2database:h2:${h2_version}"
	implementation "com.fasterxml.jackson.core:jackson-annotations:${jackson_version}"
	implementation "info.picocli:picocli:${picocli_version}"

	implementation "org.postgresql:postgresql:${postgresql_version}"
	
	implementation ("org.eclipse.digitaltwin.aas4j:aas4j-model:${aas4j_version}") {
		exclude group: "com.mycila", module: "license-maven-plugin"
	}

	// Spring boot
	implementation "org.springframework.boot:spring-boot-starter-web:${spring_boot_version}"
	implementation "org.springframework.boot:spring-boot-starter-data-jpa:${spring_boot_version}"
}